// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {initialization} from '../models';
import {menu} from '../models';
import {core} from '../models';
import {config} from '../models';
import {debug} from '../models';
import {preferences} from '../models';

export function AddContact(arg1:string,arg2:string):Promise<main.Contact>;

export function AddMasternode(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;

export function AddMasternodeConfig(arg1:main.MasternodeConfigEntry):Promise<void>;

export function AddPeer(arg1:string,arg2:string):Promise<void>;

export function AddPeers(arg1:string):Promise<Array<main.AddPeerResult>>;

export function BackupWallet():Promise<boolean>;

export function BanPeer(arg1:string,arg2:string):Promise<void>;

export function ChangeWalletPassphrase(arg1:main.ChangePassphraseRequest):Promise<main.ChangePassphraseResult>;

export function CheckDiskSpace(arg1:string):Promise<initialization.DiskSpaceInfo>;

export function CheckFirstRun():Promise<Record<string, any>>;

export function ClearDebugLog():Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateApplicationMenu():Promise<menu.Menu>;

export function CreatePaymentRequest(arg1:string,arg2:string,arg3:string,arg4:number):Promise<core.PaymentRequest>;

export function DeleteContact(arg1:string):Promise<void>;

export function DeleteMasternodeConfig(arg1:string):Promise<void>;

export function DisconnectPeer(arg1:string):Promise<void>;

export function EditContact(arg1:string,arg2:string):Promise<void>;

export function EncryptWallet(arg1:main.EncryptWalletRequest):Promise<main.EncryptWalletResult>;

export function EstimateFee(arg1:number):Promise<number>;

export function EstimateTransactionFee(arg1:main.FeeEstimateRequest):Promise<main.FeeEstimateResult>;

export function ExecuteRPCCommand(arg1:string):Promise<main.RPCCommandResult>;

export function ExplorerSearch(arg1:string):Promise<core.SearchResult>;

export function ExportConfig(arg1:string):Promise<void>;

export function ExportContactsCSV():Promise<boolean>;

export function ExportFilteredTransactionsCSV(arg1:core.TransactionFilter):Promise<boolean>;

export function ForceShutdown():Promise<void>;

export function GenerateMasternodeKey():Promise<string>;

export function GenerateReceivingAddress(arg1:string):Promise<core.ReceivingAddress>;

export function GenerateTwinsURI(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function GetAddressLabel(arg1:string):Promise<string>;

export function GetAddressTransactions(arg1:string,arg2:number,arg3:number):Promise<core.AddressTxPage>;

export function GetAddresses():Promise<Array<string>>;

export function GetAllSettingsMetadata():Promise<Record<string, main.SettingMetadata>>;

export function GetAvailableThemes():Promise<Array<main.ThemeInfo>>;

export function GetBalance():Promise<core.Balance>;

export function GetBannedPeers():Promise<Array<main.BannedPeerInfo>>;

export function GetBlockchainInfo():Promise<core.BlockchainInfo>;

export function GetConfiguration():Promise<any>;

export function GetContacts():Promise<Array<main.Contact>>;

export function GetCurrentReceivingAddress():Promise<core.ReceivingAddress>;

export function GetDaemonConfigCategories():Promise<Array<string>>;

export function GetDaemonConfigMetadata():Promise<Array<config.SettingMeta>>;

export function GetDaemonConfigValues():Promise<Record<string, any>>;

export function GetDaemonPendingRestartKeys():Promise<Array<string>>;

export function GetDataDirectoryInfo():Promise<main.DataDirectoryInfo>;

export function GetDebugEvents(arg1:main.DebugFilter):Promise<Array<main.DebugEvent>>;

export function GetDebugStatus():Promise<main.DebugStatusResponse>;

export function GetDebugSummary():Promise<debug.Summary>;

export function GetDefaultDataDirectory():Promise<string>;

export function GetExplorerAddress(arg1:string,arg2:number):Promise<core.AddressInfo>;

export function GetExplorerBlock(arg1:string):Promise<core.BlockDetail>;

export function GetExplorerTransaction(arg1:string):Promise<core.ExplorerTransaction>;

export function GetGUIConfig():Promise<Record<string, any>>;

export function GetLatestBlocks(arg1:number,arg2:number):Promise<Array<core.BlockSummary>>;

export function GetMasternodeCollateralOutpoints():Promise<Array<core.OutPoint>>;

export function GetMasternodeConfig():Promise<Array<main.MasternodeConfigEntry>>;

export function GetMasternodeList():Promise<Array<initialization.MasternodeEntry>>;

export function GetMasternodeOutputs():Promise<Array<main.MasternodeOutput>>;

export function GetMasternodeStatistics():Promise<main.MasternodeStatistics>;

export function GetMyMasternodes():Promise<Array<core.MyMasternode>>;

export function GetNetworkInfo():Promise<core.NetworkInfo>;

export function GetNetworkMasternodes():Promise<Array<core.MasternodeInfo>>;

export function GetNetworkTraffic():Promise<main.TrafficInfo>;

export function GetP2PStatus():Promise<Record<string, any>>;

export function GetPaymentRequests():Promise<Array<core.PaymentRequest>>;

export function GetPaymentStats(arg1:main.PaymentStatsFilter):Promise<main.PaymentStatsResponse>;

export function GetPeerList():Promise<Array<main.PeerDetail>>;

export function GetPendingRepairResult():Promise<main.RepairResult>;

export function GetPlatform():Promise<string>;

export function GetRPCCategoryOrder():Promise<Array<string>>;

export function GetRPCCommandCategories():Promise<Record<string, Array<string>>>;

export function GetRPCCommandDescriptions():Promise<Record<string, string>>;

export function GetRPCCommandHelp(arg1:string):Promise<string>;

export function GetRPCCommandList():Promise<Array<string>>;

export function GetRPCStatus():Promise<Record<string, any>>;

export function GetReceivingAddresses():Promise<Array<core.ReceivingAddress>>;

export function GetRecentTransactions():Promise<Array<core.Transaction>>;

export function GetRestartRequiredSettings():Promise<Array<string>>;

export function GetSettingBool(arg1:string):Promise<boolean>;

export function GetSettingInt(arg1:string):Promise<number>;

export function GetSettingInt64(arg1:string):Promise<number>;

export function GetSettingMetadata(arg1:string):Promise<main.SettingMetadata>;

export function GetSettingString(arg1:string):Promise<string>;

export function GetSettings():Promise<preferences.GUISettings>;

export function GetSettingsPath():Promise<string>;

export function GetShutdownProgress():Promise<Record<string, any>>;

export function GetStakingInfo():Promise<core.StakingInfo>;

export function GetStakingStatus():Promise<Record<string, any>>;

export function GetStoredDataDirectory():Promise<string>;

export function GetToolsInfo():Promise<main.ToolsInfo>;

export function GetTorStatus():Promise<Record<string, any>>;

export function GetTrafficHistory(arg1:number,arg2:number):Promise<Array<main.TrafficSample>>;

export function GetTransactionDetails(arg1:string):Promise<core.Transaction>;

export function GetTransactions(arg1:number):Promise<Array<core.Transaction>>;

export function GetTransactionsPage(arg1:core.TransactionFilter):Promise<core.TransactionPage>;

export function GetWalletEncryptionStatus():Promise<Record<string, any>>;

export function GetWalletStatus():Promise<main.WalletStatus>;

export function GetWalletVersion():Promise<Record<string, string>>;

export function GetWindowGeometry(arg1:string):Promise<Record<string, any>>;

export function HandleWindowMinimized():Promise<void>;

export function HasDaemonPendingRestart():Promise<boolean>;

export function HasSetting(arg1:string):Promise<boolean>;

export function ImportConfig(arg1:string):Promise<void>;

export function InitializeDataDirectory(arg1:string):Promise<void>;

export function InitiateShutdown():Promise<void>;

export function IsDevMockMode():Promise<boolean>;

export function IsMasternodeCollateral(arg1:string,arg2:number):Promise<main.MasternodeCollateralInfo>;

export function IsShutdownComplete():Promise<boolean>;

export function IsShuttingDown():Promise<boolean>;

export function ListLockUnspent():Promise<Array<core.OutPoint>>;

export function ListUnspent(arg1:number,arg2:number):Promise<Array<core.UTXO>>;

export function LoadConfiguration(arg1:string):Promise<void>;

export function LockUnspent(arg1:boolean,arg2:Array<core.OutPoint>):Promise<void>;

export function LockWallet():Promise<main.LockWalletResult>;

export function ReloadConfiguration():Promise<void>;

export function ReloadMasternodeConfig():Promise<void>;

export function RemoveMasternode(arg1:string):Promise<void>;

export function RemovePaymentRequest(arg1:string,arg2:number):Promise<void>;

export function RemovePeerAlias(arg1:string):Promise<void>;

export function ResetPreferences():Promise<void>;

export function ResetSettings():Promise<void>;

export function RestartApp():Promise<void>;

export function RestoreToStakingOnlyMode():Promise<main.RestoreToStakingOnlyModeResult>;

export function SaveCSVFile(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function SaveWindowGeometry(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:boolean):Promise<void>;

export function SelectDataDirectory():Promise<string>;

export function SendTransaction(arg1:string,arg2:number):Promise<main.SendTransactionResult>;

export function SendTransactionMulti(arg1:main.SendTransactionMultiRequest):Promise<main.SendTransactionResult>;

export function SendTransactionWithOptions(arg1:string,arg2:number,arg3:main.SendTransactionOptions):Promise<main.SendTransactionResult>;

export function SetAddressLabel(arg1:string,arg2:string):Promise<void>;

export function SetDaemonConfigValue(arg1:string,arg2:any):Promise<void>;

export function SetPeerAlias(arg1:string,arg2:string):Promise<void>;

export function SetSettingBool(arg1:string,arg2:boolean):Promise<void>;

export function SetSettingInt(arg1:string,arg2:number):Promise<void>;

export function SetSettingInt64(arg1:string,arg2:number):Promise<void>;

export function SetSettingString(arg1:string,arg2:string):Promise<void>;

export function SetTrayIconVisible(arg1:boolean):Promise<void>;

export function SetWindowToMain():Promise<void>;

export function SetWindowToSplash():Promise<void>;

export function SignMessage(arg1:string,arg2:string):Promise<string>;

export function StartAllMasternodes():Promise<void>;

export function StartInitialization():Promise<void>;

export function StartMasternode(arg1:string):Promise<void>;

export function StartMissingMasternodes():Promise<number>;

export function StartP2P():Promise<void>;

export function StartRPCServer():Promise<void>;

export function StartStaking():Promise<void>;

export function ToggleStaking(arg1:boolean):Promise<Record<string, any>>;

export function UnbanPeer(arg1:string):Promise<void>;

export function UnlockWallet(arg1:main.UnlockWalletRequest):Promise<main.UnlockWalletResult>;

export function UpdateMasternodeConfig(arg1:string,arg2:main.MasternodeConfigEntry):Promise<void>;

export function UpdateSetting(arg1:string,arg2:any):Promise<void>;

export function UpdateSettings(arg1:Record<string, any>):Promise<void>;

export function ValidateAddress(arg1:string):Promise<core.AddressValidation>;

export function ValidateConfiguration():Promise<void>;

export function ValidateDataDirectory(arg1:string):Promise<void>;

export function VerifyMessage(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function WalletRepair(arg1:string):Promise<void>;
