// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddContact(arg1, arg2) {
  return window['go']['main']['App']['AddContact'](arg1, arg2);
}

export function AddMasternode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddMasternode'](arg1, arg2, arg3, arg4, arg5);
}

export function AddMasternodeConfig(arg1) {
  return window['go']['main']['App']['AddMasternodeConfig'](arg1);
}

export function AddPeer(arg1, arg2) {
  return window['go']['main']['App']['AddPeer'](arg1, arg2);
}

export function AddPeers(arg1) {
  return window['go']['main']['App']['AddPeers'](arg1);
}

export function BackupWallet() {
  return window['go']['main']['App']['BackupWallet']();
}

export function BanPeer(arg1, arg2) {
  return window['go']['main']['App']['BanPeer'](arg1, arg2);
}

export function ChangeWalletPassphrase(arg1) {
  return window['go']['main']['App']['ChangeWalletPassphrase'](arg1);
}

export function CheckDiskSpace(arg1) {
  return window['go']['main']['App']['CheckDiskSpace'](arg1);
}

export function CheckFirstRun() {
  return window['go']['main']['App']['CheckFirstRun']();
}

export function ClearDebugLog() {
  return window['go']['main']['App']['ClearDebugLog']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateApplicationMenu() {
  return window['go']['main']['App']['CreateApplicationMenu']();
}

export function CreatePaymentRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreatePaymentRequest'](arg1, arg2, arg3, arg4);
}

export function DeleteContact(arg1) {
  return window['go']['main']['App']['DeleteContact'](arg1);
}

export function DeleteMasternodeConfig(arg1) {
  return window['go']['main']['App']['DeleteMasternodeConfig'](arg1);
}

export function DisconnectPeer(arg1) {
  return window['go']['main']['App']['DisconnectPeer'](arg1);
}

export function EditContact(arg1, arg2) {
  return window['go']['main']['App']['EditContact'](arg1, arg2);
}

export function EncryptWallet(arg1) {
  return window['go']['main']['App']['EncryptWallet'](arg1);
}

export function EstimateFee(arg1) {
  return window['go']['main']['App']['EstimateFee'](arg1);
}

export function EstimateTransactionFee(arg1) {
  return window['go']['main']['App']['EstimateTransactionFee'](arg1);
}

export function ExecuteRPCCommand(arg1) {
  return window['go']['main']['App']['ExecuteRPCCommand'](arg1);
}

export function ExplorerSearch(arg1) {
  return window['go']['main']['App']['ExplorerSearch'](arg1);
}

export function ExportConfig(arg1) {
  return window['go']['main']['App']['ExportConfig'](arg1);
}

export function ExportContactsCSV() {
  return window['go']['main']['App']['ExportContactsCSV']();
}

export function ExportFilteredTransactionsCSV(arg1) {
  return window['go']['main']['App']['ExportFilteredTransactionsCSV'](arg1);
}

export function ForceShutdown() {
  return window['go']['main']['App']['ForceShutdown']();
}

export function GenerateMasternodeKey() {
  return window['go']['main']['App']['GenerateMasternodeKey']();
}

export function GenerateReceivingAddress(arg1) {
  return window['go']['main']['App']['GenerateReceivingAddress'](arg1);
}

export function GenerateTwinsURI(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateTwinsURI'](arg1, arg2, arg3, arg4);
}

export function GetAddressLabel(arg1) {
  return window['go']['main']['App']['GetAddressLabel'](arg1);
}

export function GetAddressTransactions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAddressTransactions'](arg1, arg2, arg3);
}

export function GetAddresses() {
  return window['go']['main']['App']['GetAddresses']();
}

export function GetAllSettingsMetadata() {
  return window['go']['main']['App']['GetAllSettingsMetadata']();
}

export function GetAvailableThemes() {
  return window['go']['main']['App']['GetAvailableThemes']();
}

export function GetBalance() {
  return window['go']['main']['App']['GetBalance']();
}

export function GetBannedPeers() {
  return window['go']['main']['App']['GetBannedPeers']();
}

export function GetBlockchainInfo() {
  return window['go']['main']['App']['GetBlockchainInfo']();
}

export function GetConfiguration() {
  return window['go']['main']['App']['GetConfiguration']();
}

export function GetContacts() {
  return window['go']['main']['App']['GetContacts']();
}

export function GetCurrentReceivingAddress() {
  return window['go']['main']['App']['GetCurrentReceivingAddress']();
}

export function GetDaemonConfigCategories() {
  return window['go']['main']['App']['GetDaemonConfigCategories']();
}

export function GetDaemonConfigMetadata() {
  return window['go']['main']['App']['GetDaemonConfigMetadata']();
}

export function GetDaemonConfigValues() {
  return window['go']['main']['App']['GetDaemonConfigValues']();
}

export function GetDaemonPendingRestartKeys() {
  return window['go']['main']['App']['GetDaemonPendingRestartKeys']();
}

export function GetDataDirectoryInfo() {
  return window['go']['main']['App']['GetDataDirectoryInfo']();
}

export function GetDebugEvents(arg1) {
  return window['go']['main']['App']['GetDebugEvents'](arg1);
}

export function GetDebugStatus() {
  return window['go']['main']['App']['GetDebugStatus']();
}

export function GetDebugSummary() {
  return window['go']['main']['App']['GetDebugSummary']();
}

export function GetDefaultDataDirectory() {
  return window['go']['main']['App']['GetDefaultDataDirectory']();
}

export function GetExplorerAddress(arg1, arg2) {
  return window['go']['main']['App']['GetExplorerAddress'](arg1, arg2);
}

export function GetExplorerBlock(arg1) {
  return window['go']['main']['App']['GetExplorerBlock'](arg1);
}

export function GetExplorerTransaction(arg1) {
  return window['go']['main']['App']['GetExplorerTransaction'](arg1);
}

export function GetGUIConfig() {
  return window['go']['main']['App']['GetGUIConfig']();
}

export function GetLatestBlocks(arg1, arg2) {
  return window['go']['main']['App']['GetLatestBlocks'](arg1, arg2);
}

export function GetMasternodeCollateralOutpoints() {
  return window['go']['main']['App']['GetMasternodeCollateralOutpoints']();
}

export function GetMasternodeConfig() {
  return window['go']['main']['App']['GetMasternodeConfig']();
}

export function GetMasternodeList() {
  return window['go']['main']['App']['GetMasternodeList']();
}

export function GetMasternodeOutputs() {
  return window['go']['main']['App']['GetMasternodeOutputs']();
}

export function GetMasternodeStatistics() {
  return window['go']['main']['App']['GetMasternodeStatistics']();
}

export function GetMyMasternodes() {
  return window['go']['main']['App']['GetMyMasternodes']();
}

export function GetNetworkInfo() {
  return window['go']['main']['App']['GetNetworkInfo']();
}

export function GetNetworkMasternodes() {
  return window['go']['main']['App']['GetNetworkMasternodes']();
}

export function GetNetworkTraffic() {
  return window['go']['main']['App']['GetNetworkTraffic']();
}

export function GetP2PStatus() {
  return window['go']['main']['App']['GetP2PStatus']();
}

export function GetPaymentRequests() {
  return window['go']['main']['App']['GetPaymentRequests']();
}

export function GetPaymentStats(arg1) {
  return window['go']['main']['App']['GetPaymentStats'](arg1);
}

export function GetPeerList() {
  return window['go']['main']['App']['GetPeerList']();
}

export function GetPendingRepairResult() {
  return window['go']['main']['App']['GetPendingRepairResult']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetRPCCategoryOrder() {
  return window['go']['main']['App']['GetRPCCategoryOrder']();
}

export function GetRPCCommandCategories() {
  return window['go']['main']['App']['GetRPCCommandCategories']();
}

export function GetRPCCommandDescriptions() {
  return window['go']['main']['App']['GetRPCCommandDescriptions']();
}

export function GetRPCCommandHelp(arg1) {
  return window['go']['main']['App']['GetRPCCommandHelp'](arg1);
}

export function GetRPCCommandList() {
  return window['go']['main']['App']['GetRPCCommandList']();
}

export function GetRPCStatus() {
  return window['go']['main']['App']['GetRPCStatus']();
}

export function GetReceivingAddresses() {
  return window['go']['main']['App']['GetReceivingAddresses']();
}

export function GetRecentTransactions() {
  return window['go']['main']['App']['GetRecentTransactions']();
}

export function GetRestartRequiredSettings() {
  return window['go']['main']['App']['GetRestartRequiredSettings']();
}

export function GetSettingBool(arg1) {
  return window['go']['main']['App']['GetSettingBool'](arg1);
}

export function GetSettingInt(arg1) {
  return window['go']['main']['App']['GetSettingInt'](arg1);
}

export function GetSettingInt64(arg1) {
  return window['go']['main']['App']['GetSettingInt64'](arg1);
}

export function GetSettingMetadata(arg1) {
  return window['go']['main']['App']['GetSettingMetadata'](arg1);
}

export function GetSettingString(arg1) {
  return window['go']['main']['App']['GetSettingString'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSettingsPath() {
  return window['go']['main']['App']['GetSettingsPath']();
}

export function GetShutdownProgress() {
  return window['go']['main']['App']['GetShutdownProgress']();
}

export function GetStakingInfo() {
  return window['go']['main']['App']['GetStakingInfo']();
}

export function GetStakingStatus() {
  return window['go']['main']['App']['GetStakingStatus']();
}

export function GetStoredDataDirectory() {
  return window['go']['main']['App']['GetStoredDataDirectory']();
}

export function GetToolsInfo() {
  return window['go']['main']['App']['GetToolsInfo']();
}

export function GetTorStatus() {
  return window['go']['main']['App']['GetTorStatus']();
}

export function GetTrafficHistory(arg1, arg2) {
  return window['go']['main']['App']['GetTrafficHistory'](arg1, arg2);
}

export function GetTransactionDetails(arg1) {
  return window['go']['main']['App']['GetTransactionDetails'](arg1);
}

export function GetTransactions(arg1) {
  return window['go']['main']['App']['GetTransactions'](arg1);
}

export function GetTransactionsPage(arg1) {
  return window['go']['main']['App']['GetTransactionsPage'](arg1);
}

export function GetWalletEncryptionStatus() {
  return window['go']['main']['App']['GetWalletEncryptionStatus']();
}

export function GetWalletStatus() {
  return window['go']['main']['App']['GetWalletStatus']();
}

export function GetWalletVersion() {
  return window['go']['main']['App']['GetWalletVersion']();
}

export function GetWindowGeometry(arg1) {
  return window['go']['main']['App']['GetWindowGeometry'](arg1);
}

export function HandleWindowMinimized() {
  return window['go']['main']['App']['HandleWindowMinimized']();
}

export function HasDaemonPendingRestart() {
  return window['go']['main']['App']['HasDaemonPendingRestart']();
}

export function HasSetting(arg1) {
  return window['go']['main']['App']['HasSetting'](arg1);
}

export function ImportConfig(arg1) {
  return window['go']['main']['App']['ImportConfig'](arg1);
}

export function InitializeDataDirectory(arg1) {
  return window['go']['main']['App']['InitializeDataDirectory'](arg1);
}

export function InitiateShutdown() {
  return window['go']['main']['App']['InitiateShutdown']();
}

export function IsDevMockMode() {
  return window['go']['main']['App']['IsDevMockMode']();
}

export function IsMasternodeCollateral(arg1, arg2) {
  return window['go']['main']['App']['IsMasternodeCollateral'](arg1, arg2);
}

export function IsShutdownComplete() {
  return window['go']['main']['App']['IsShutdownComplete']();
}

export function IsShuttingDown() {
  return window['go']['main']['App']['IsShuttingDown']();
}

export function ListLockUnspent() {
  return window['go']['main']['App']['ListLockUnspent']();
}

export function ListUnspent(arg1, arg2) {
  return window['go']['main']['App']['ListUnspent'](arg1, arg2);
}

export function LoadConfiguration(arg1) {
  return window['go']['main']['App']['LoadConfiguration'](arg1);
}

export function LockUnspent(arg1, arg2) {
  return window['go']['main']['App']['LockUnspent'](arg1, arg2);
}

export function LockWallet() {
  return window['go']['main']['App']['LockWallet']();
}

export function ReloadConfiguration() {
  return window['go']['main']['App']['ReloadConfiguration']();
}

export function ReloadMasternodeConfig() {
  return window['go']['main']['App']['ReloadMasternodeConfig']();
}

export function RemoveMasternode(arg1) {
  return window['go']['main']['App']['RemoveMasternode'](arg1);
}

export function RemovePaymentRequest(arg1, arg2) {
  return window['go']['main']['App']['RemovePaymentRequest'](arg1, arg2);
}

export function RemovePeerAlias(arg1) {
  return window['go']['main']['App']['RemovePeerAlias'](arg1);
}

export function ResetPreferences() {
  return window['go']['main']['App']['ResetPreferences']();
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RestoreToStakingOnlyMode() {
  return window['go']['main']['App']['RestoreToStakingOnlyMode']();
}

export function SaveCSVFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCSVFile'](arg1, arg2, arg3);
}

export function SaveWindowGeometry(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveWindowGeometry'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SelectDataDirectory() {
  return window['go']['main']['App']['SelectDataDirectory']();
}

export function SendTransaction(arg1, arg2) {
  return window['go']['main']['App']['SendTransaction'](arg1, arg2);
}

export function SendTransactionMulti(arg1) {
  return window['go']['main']['App']['SendTransactionMulti'](arg1);
}

export function SendTransactionWithOptions(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendTransactionWithOptions'](arg1, arg2, arg3);
}

export function SetAddressLabel(arg1, arg2) {
  return window['go']['main']['App']['SetAddressLabel'](arg1, arg2);
}

export function SetDaemonConfigValue(arg1, arg2) {
  return window['go']['main']['App']['SetDaemonConfigValue'](arg1, arg2);
}

export function SetPeerAlias(arg1, arg2) {
  return window['go']['main']['App']['SetPeerAlias'](arg1, arg2);
}

export function SetSettingBool(arg1, arg2) {
  return window['go']['main']['App']['SetSettingBool'](arg1, arg2);
}

export function SetSettingInt(arg1, arg2) {
  return window['go']['main']['App']['SetSettingInt'](arg1, arg2);
}

export function SetSettingInt64(arg1, arg2) {
  return window['go']['main']['App']['SetSettingInt64'](arg1, arg2);
}

export function SetSettingString(arg1, arg2) {
  return window['go']['main']['App']['SetSettingString'](arg1, arg2);
}

export function SetTrayIconVisible(arg1) {
  return window['go']['main']['App']['SetTrayIconVisible'](arg1);
}

export function SetWindowToMain() {
  return window['go']['main']['App']['SetWindowToMain']();
}

export function SetWindowToSplash() {
  return window['go']['main']['App']['SetWindowToSplash']();
}

export function SignMessage(arg1, arg2) {
  return window['go']['main']['App']['SignMessage'](arg1, arg2);
}

export function StartAllMasternodes() {
  return window['go']['main']['App']['StartAllMasternodes']();
}

export function StartInitialization() {
  return window['go']['main']['App']['StartInitialization']();
}

export function StartMasternode(arg1) {
  return window['go']['main']['App']['StartMasternode'](arg1);
}

export function StartMissingMasternodes() {
  return window['go']['main']['App']['StartMissingMasternodes']();
}

export function StartP2P() {
  return window['go']['main']['App']['StartP2P']();
}

export function StartRPCServer() {
  return window['go']['main']['App']['StartRPCServer']();
}

export function StartStaking() {
  return window['go']['main']['App']['StartStaking']();
}

export function ToggleStaking(arg1) {
  return window['go']['main']['App']['ToggleStaking'](arg1);
}

export function UnbanPeer(arg1) {
  return window['go']['main']['App']['UnbanPeer'](arg1);
}

export function UnlockWallet(arg1) {
  return window['go']['main']['App']['UnlockWallet'](arg1);
}

export function UpdateMasternodeConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateMasternodeConfig'](arg1, arg2);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function ValidateAddress(arg1) {
  return window['go']['main']['App']['ValidateAddress'](arg1);
}

export function ValidateConfiguration() {
  return window['go']['main']['App']['ValidateConfiguration']();
}

export function ValidateDataDirectory(arg1) {
  return window['go']['main']['App']['ValidateDataDirectory'](arg1);
}

export function VerifyMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['VerifyMessage'](arg1, arg2, arg3);
}

export function WalletRepair(arg1) {
  return window['go']['main']['App']['WalletRepair'](arg1);
}
